# 파일 경로: mainpc/docker-compose.yml
version: '3.8'
services:
  ai-trainer:
    image: nhbot-trainer
    container_name: nhbot-trainer-container
    ports:
      - "5000:5000"  # ⭐ Flask API 포트 매핑 추가
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - .:/app
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1  # ⭐ Flask 로그 실시간 출력
    command: python ai_server.py  # ⭐ Flask 서버 실행으로 변경
    restart: unless-stopped